name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ubuntu_wayland:
    name: Build Ubuntu Wayland
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          host: linux

      - name: Install Vulkan SDK
        run: |
          sudo apt update
          sudo apt install libvulkan-dev libwayland-dev

      - name: Build
        env:
          TARGET_PLATFORM: wayland
        run: |
          echo ${TARGET_PLATFORM}
          PATH="/opt/qt512/bin:$PATH"
          CXX="clang++"
          qmake DEFINES+=WAYLAND CONFIG+=release PREFIX=/usr
          make INSTALL_ROOT=appdir install ; find appdir/
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          export VERSION=${TARGET_PLATFORM}
          cp vulkanCapsViewer.png appdir/usr/share/icons/hicolor/256x256/apps/vulkanCapsViewer.png
          ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/* -appimage -exclude-libs=libwayland-client.so
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: Vulkan_Caps_Viewer-wayland-x86_64.AppImage
